# Generated by Django 6.0.2 on 2026-04-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_place_opening_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='phone_number',
            field=models.CharField(blank=True, default='+965 123 45678', max_length=30),
        ),
    ]
